### PR TITLE
remove documents feature

### PR DESCRIPTION
**Pull request by chetbae**
#(https://github.com/DDMAL/Neon/issues/690)
#(https://github.com/DDMAL/Neon/issues/801)

Option to remove pages or manuscripts for user-selected documents:
(Select a user-provided document) -> (page -or- manuscript) -> ([drop-down select] Open or __Delete__)

*Also added spinning icon for submit buttons to indicate that background processes are happening.

### CODE REVIEW

**Comment by JoyfulGen** [comment]
Looks good to me! Will it be possible to select more than one file to delete at a time?

**Comment by chetbae** [comment]
> Looks good to me! Will it be possible to select more than one file to delete at a time?

@JoyfulGen Not as of now, but I can make that possible easily! Would that be preferable?

**Review by yinanazhou — APPROVED** [review]

**Review by JoyfulGen — APPROVED** [review]

**Comment by JoyfulGen** [comment]
> > Looks good to me! Will it be possible to select more than one file to delete at a time?
> 
> @JoyfulGen Not as of now, but I can make that possible easily! Would that be preferable?

Yes, that would be awesome!

**Comment by chetbae** [comment]
Turns out the multiple selection feature was harder to implement than I thought because of the way the index is set up. Merging the single selection now, but better selection methods coming!

**Pull request merged**
